/*import "./QuerySupportTest";
import "./EventSupportTest";
import "./ManipulationSupportTest";
import "./DataSupportTest";
import "./AttributeSupportTest";
import "./HtmlClassSupportTest";
import "./ValueSupportTest";
import "./ReadyEventSupportTest";
import "./ListSupportTest";*/
import "./ShowHideSupportTest";